services:
  postgres:
    image: postgres
    container_name: pg_container_sporkbin
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: requestbin
    ports:
      - '5432:5432'

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    command: ['--noauth']
    environment:
      MONGO_INITDB_DATABASE: spork-bin
